### PR TITLE
examples: if sudo is required, sudo the script instead of exiting

### PR DESCRIPTION
**Pull request by dgonyeo**
I think this is a little more user friendly.

### CODE REVIEW

**Comment by jonboulle** [comment]
ehh, -1

**Comment by jonboulle** [comment]
Let's not second guess users. One of the goals with appc is to make security as explicit as possible.

**Comment by dgonyeo** [comment]
got it

**Comment by ecnahc515** [comment]
What about just printing a warning and exiting before doing anything?

**Comment by dgonyeo** [comment]
That's what the script currently does.

**Comment by jonboulle** [comment]
isn't that exactly what we do?

**Comment by ecnahc515** [comment]
Oh, your right. Ignore.

**Pull request closed without merging**
