### PR TITLE
*: replaced godep with glide

### PR DESCRIPTION
**Pull request by dgonyeo**
Godep was continually being a drain on development resources of acbuild,
and thus this commit replaces godep with glide. Glide takes advantage of
the golang vendor experiment, and thus this change will drop support for
versions of Go less than 1.5.

The biggest impact this change has is that dependencies are no longer
vendored with acbuild, and are instead fetched at compile time by the
build script. This is done by checking if the `vendor` directory exists,
and running `glide install` if it is not.

Fixes https://github.com/appc/acbuild/issues/98. Replaces https://github.com/appc/acbuild/pull/157.

### CODE REVIEW

**Comment by jonboulle** [comment]
Why do you not want to vendor the deps?

Derek Gonyeo <notifications@github.com> schrieb am Fr., 26. Feb. 2016 20:23:

**Comment by dgonyeo** [comment]
It's not something that's as nicely supported with glide. It leaves the .git directories in what it fetches, and I didn't see an easy way to disable that.

I see two arguments to not want to move away from vendoring our dependencies:
- What if one of our dependencies vanishes from github?
 -   We have a local copy on our machines (because it'll be sitting in acbuild's vendor directory), and can throw up a fork of the project.
- What if github goes down?
 -   This will only impact users who haven't yet built acbuild once, and chances are if someone who wants to build acbuild is at this stage then they don't have acbuild either, and won't be able to get it anyway.

I also think that glide's model will make it a good amount easier to work on both acbuild and one of acbuild's dependencies concurrently, since you can just `cd` into `vendor/github.com/the/dependency`, make changes, see the impact on acbuild, and when you're done commit and push inside the vendored repo.

**Comment by sgotti** [comment]
Hi, as I also started experimenting with glide and I'd like to share what I learned since I'd prefer to vendor dependencies:

* Glide doesn't remove .git and other VCS directories. But you can easily do this and now there's a tool to do this:

http://engineeredweb.com/blog/2016/glide-strip-vendor-vcs/

* Glide doesn't remove unused packages so the created vendor, also with VCS data stripped out, remains with unneeded files (for example importing just the etcd client package imports the whole etcd project). The explanation is related to licensing and project modifications:

http://engineeredweb.com/blog/2016/go-why-not-strip-unused-pkgs/

But if you are sure of not causing license issues you can probably write a tool (I'm going to do this if it doesn't exists) that, given the glide.lock will remove all the files outside the import or subpackages (if the import have sub packages).

* Just for completeness (but it's a general info and not related to glide) as the glide faq says, vendoring is good for the final application but with a package meant to be used by other projects it can cause problems in some cases:
https://github.com/mattfarina/golang-broken-vendor

But this is a problem present also with old style Godep vendoring/rewriting.

**Comment by jonboulle** [comment]
@sgotti thanks for letting us know your experience! Would you mind sharing
more about why you wanted to move away from Godep and how glide improves?

**Comment by sgotti** [comment]
@jonboulle sure. I'm currently not in the position to suggest e tool over another. I was intrigued on how it tries to manage dependencies like npm, pip, bundler using a config file and lock files, it tries to implements semver dependencies and read config from other vendor tools like godeps, gb etc...

Obviously, since golang is really distributed and doesn't have a central repository, there are some difference with other languages/tools.

One interesting thing is that it doesn't needs packages in your gopath but it will check them out directly inside your project (or copy them from a cache dir or from the gopath but then checking out the right version inside you project).

On the other side, glide doesn't enforce you to commit your vendor directory. This is causing me some headache since many projects (myself too) wants to commit it (for a lot of good reasons), but having or not having nested vendor directories have a different compilation behavior. I opened github.com/Masterminds#303 to talk about this.

Additionally, if I want to commit, and I'm sure to not cause licenses violations, I'd like to remove as much as possible from the vendor directory. I wrote a tool to do this (https://github.com/sgotti/glide-vc) (with some changes in flight, see the opened PRs)

**Comment by sgotti** [comment]
After triggering some discussions on Masterminds/glide#303, glide 0.10 has much improved the vendor handling (http://engineeredweb.com/blog/2016/glide-0.10.0/)

Now you can easily remove nested vendor folders. This obviously means that you won't have problems like [this](https://github.com/mattfarina/golang-broken-vendor) but you can't have multiple versions of the same package (since all deps are flattened). So if you have two dependencies that depends on incompatible version of `pkgA` you have to find a fix for making them work together.

actually my preferred workflow is this one:

* create a glide.yaml (`glide create`, if already using godeps it'll convert them from godeps)
* Update it (I prefer to specificy semvers tagged releases when possibile)
* `rm -rf vendor` (I like to treat my vendor as a scratch and be able to recreate it every time)
* `glide update -u -s -v --cache` # This will populate the vendor dir, remove VCS data and strip vendor (also undo godeps import rewriting). `--cache` is very useful to avoid git cloning deps every time I run it, you can also use `--cache-gopath` and `--use-gopath` instead of having a dedicate cache dir.
* Test, fix glide.yaml for incompatibilities (for example force subdependency versions if needed)
* Before committing `glide.yaml`, `glide.lock` and `vendor/`, super strip `vendor/` removing (if licenses will permit it) all unneeded files using glide-vc (https://github.com/sgotti/glide-vc):
`glide-vc --only-go --no-tests`

**Comment by jonboulle** [comment]
cross-linking https://github.com/sorintlab/stolon/pull/131

**Comment by dgonyeo** [comment]
Revisited this, tests now pass. Now vendors dependencies, unlike when I originally made this PR (uses glide flags to trip VCS info). Added `Documentation/development-guide.md` with a short guide on using glide.

**Comment by dgonyeo** [comment]
Oh, and due to switching to using `vendor`, this commit drops go 1.4 from the travis tests.

**Comment by jonboulle** [comment]
@dgonyeo there is a tonne of unused stuff in there - is this post-`glide-vc`?

**Comment by dgonyeo** [comment]
No it's not. Just ran `glide-vc`, updated the docs to state that it should be used and how to use it, and added these changes to the PR.

**Pull request closed without merging**
