### PR TITLE
release: added changelog for release v0.1.0

### PR DESCRIPTION
**Pull request by dgonyeo**
Added changelog for acbuild's first release. The release will be tagged once this PR is accepted.

### CODE REVIEW

**Comment by jonboulle** [comment]
Please use semver. v0.1.0.

**Comment by dgonyeo** [comment]
done

**Comment by jonboulle** [comment]
OK, after OOB discussion, let's just proceed with the version as-is for now. But please add a comment to the notes describing which version of the schema this release of acbuild implements.

**Comment by dgonyeo** [comment]
that look good?

**Comment by jonboulle** [comment]
hrm, how about using the actual sha. Check out Godeps/Godeps.json for example.

**Comment by dgonyeo** [comment]
I was going off of what `acbuild version` gave me.

That look better?

**Comment by jonboulle** [comment]
:ship: :shipit: :sheep:

**Pull request merged**
