### PR TITLE
set-working-directory: added command to set the ACI's working directory

### PR DESCRIPTION
**Pull request by dgonyeo**
Fixes https://github.com/appc/acbuild/issues/78

### CODE REVIEW

**Comment by dgonyeo** [comment]
I was uncertain how to go about unsetting an ACI's working directory, right now the command to do it is:

```
acbuild set-wd ""
```

I don't think that's as intuitive as it could be. Maybe instead the syntax should be:

```
acbuild wd set /root
acbuild wd unset
```

This would also apply to set-exec, since that's another field that is allowed to not be set.

Thoughts?

**Comment by jonboulle** [comment]
I have a dusty memory of @vcaputo having an opinion on this from a previous discussion sometime...

**Comment by ecnahc515** [comment]
Isn't the default working directory `/` usually? I know that's the case in docker. If it is, then the 'unset' is just `acbuild wd set /`.

**Comment by dgonyeo** [comment]
Not that it would impact the user, but there is a difference in the manifest between the value not existing and the value being "/". Should acbuild differentiate between the two?

**Comment by ecnahc515** [comment]
The spec says it's optional, but the default is `/` but it's overridable by the ACE, so if you always set it, then it's possible the ACE wont override it with it's own custom default. It seems weird that the ACE can change the default at all, so I personally think it should always default to `/`.

**Comment by dgonyeo** [comment]
I'm still going to want to support unsetting the exec field. Maybe just a flag would be sufficient? Something like one of these:
```
acbuild set-exec --unset
acbuild set-exec --empty
acbuild set-exec --reset
```
And if the flag exists there I'd be inclined to add it to `set-wd`. I'm not opposed to defaulting it to `/`, but I still want to provide a way to unset it.

**Comment by dgonyeo** [comment]
Unsetting it is more of an edge case that I can worry about in a future PR. Thoughts on merging this @jonboulle ?

**Comment by jonboulle** [comment]
Sure, let's cross that bridge when we come to it.

**Pull request merged**
