### PR TITLE
replace-manifest: added command to replace manifest with a new one

### PR DESCRIPTION
**Pull request by dgonyeo**
`replace-manifest` will overwrite the manifest in the current ACI with a given new ACI. Analogous to `actool`'s `patch-manifest --manifest=thing`

### CODE REVIEW

**Comment by ecnahc515** [comment]
Maybe `set-manifest`?

**Comment by dgonyeo** [comment]
That would be fine with me. I went with `new-manifest` to differentiate it from all the `set-*` commands, since it's not just altering a value in the manifest.

**Comment by ecnahc515** [comment]
Yeah, but it's really an 'overwrite' operation, so I like the word `set`. I also feel similarly about the `add` commands after using it this weekend, but that could be discussed more later.

**Comment by dgonyeo** [comment]
The `add` commands usually append to a list, unless you're adding something that already exists.

**Comment by jonboulle** [comment]
replace-manifest ?

**Comment by dgonyeo** [comment]
I like `replace-manifest` more. New commit pushed.

**Comment by ecnahc515** [comment]
Does `replace` make sense when you have an ACI that doesn't already contain a manifest?

**Comment by dgonyeo** [comment]
I don't know if there ever would be such a situation. Even when you create a minimal ACI with acbuild begin it has a manifest.

**Comment by jonboulle** [comment]
Right, aiui replace is always appropriate.

**Comment by jonboulle** [comment]
Hm. I wonder if the lib function should operate on a file or an imagemanifest object.

**Comment by dgonyeo** [comment]
I *think* if it took an ImageManifest that it would be the only place a user of the library needs to pull in something from the appc/spec repo. I might be wrong on that though, not at my laptop.

**Comment by ecnahc515** [comment]
@dgonyeo I'm thinking a case where we have a rootfs in a tarball but without the manifest, ie: someone made their own tarball but want to use acbuild to create a manifest

**Comment by dgonyeo** [comment]
That's not a valid ACI then. In that case I'd suggest the person untar the rootfs, acbuild begin, and acbuild copy rootfs /

**Comment by jonboulle** [comment]
LGTM but please rename the PR

**Pull request merged**
