### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by derekchiang**
WIP.  Tracking #5.

### CODE REVIEW

**Comment by jonboulle** [comment]
Why the move from cobra to cli?

**Comment by jonboulle** [comment]
I like where this is going but will hold off on reviewing until you let us know it's ready for one

**Comment by derekchiang** [comment]
TBH I just wanted to try out cli.  I think it's marginally better in that it saves you from storing flags as global variables.

And yeah, I will let you guys know when this is ready for review.

**Comment by jonboulle** [comment]
@derekchiang what's the status here?

**Comment by derekchiang** [comment]
I've been taking a break in China therefore the inactivity.  Before that I had been meaning to add more tests and clean up the code a bit but I guess that shouldn't block code reviews.  So yeah, please give the code a review!  @jonboulle @klizhentas 

Currently the tool is very much usable, although its image discovery mechanism is limited to file system.  Eventually we will probably want to borrow the image discovery code from `rkt`.

**Comment by klizhentas** [comment]
k, the first comment: can you please split this into two commits: the code itself and then vendored part. Right now it's quite hard to review the whole thing.

**Comment by derekchiang** [comment]
I seem to have done something peculiar and now Github won't let me reopen this PR.  I've opened a new PR in #10.  Please look there instead.  As Sasha suggested, I've broken done the PR into 2 commits.

**Pull request closed without merging**
