### PR TITLE
godep: update appc/spec dependency

### PR DESCRIPTION
**Pull request by dgonyeo**
acbuild was using an older version of the appc/spec, which was causing
an issue with GetACI in registry/registry.go when the exec command of
a dependency wasn't set.

### CODE REVIEW

**Comment by jonboulle** [comment]
Why isn't godeps.json updated?

**Comment by jonboulle** [comment]
LGTM

**Comment by jonboulle** [comment]
@dgonyeo can you please look at #37 soon?

**Comment by dgonyeo** [comment]
Yup, was planning on asking you about the best way to go about that in person tomorrow.

**Pull request merged**
